### ISSUE TITLE
Some glitch on second page

### ISSUE THREAD

**Issue by Serenade600** [mikemahoney218/quarto-tandf#1]
The html  https://mike.quarto.pub/demo-taylor-and-francis-template/ has some glitch on second page
![image](https://user-images.githubusercontent.com/40297752/189509187-59efcbdc-1198-4810-8f5d-a34bda526d06.png)

**Comment by mikemahoney218** [comment]
Thanks; I can't seem to reproduce this locally (rendering this on my own PC looks as you'd expect) but I do also see it in the demo PDF. I'll keep looking.

**Comment by mikemahoney218** [comment]
Thanks for the report! This seems to be fixed with newer versions of Quarto, and is now fixed on the demo.
