### ISSUE TITLE
Word format possible? 

### ISSUE THREAD

**Issue by rfaridi** [mikemahoney218/quarto-tandf#2]
Hello, thanks a lot for this extension. It was very helpful.  Since quite a few T&F journals require word format submission, will it be possible to add docx format with this extension?

**Comment by mikemahoney218** [comment]
Hi @rfaridi ! Sorry, but this isn't something I'm going to do; I don't use Word and I don't need the Word template for my own work, so I haven't looked into the T&F Word template at all, or at how one even writes a Word template for Quarto.

If you wind up making a Word template, let me know and I'll happily link to it from this project! And just as a personal observation, I find that a lot of journals whose submission instructions only mention Word documents are also perfectly happy to accept latex files; they just want to make sure they're getting text files and not solely the rendered PDF.
