### ISSUE TITLE
Appendix

### ISSUE THREAD

**Issue by usman-afzali** [mikemahoney218/quarto-tandf#3]
How can we add Appendices after the References list? I am using your template for a paper (it's amazing by the way - thank you) and was wandering if you could help with this please?

**Comment by usman-afzali** [comment]
Actually, I figured it out. Thank you for the amazing template.

**Comment by mikemahoney218** [comment]
Sorry for the delay @usman-afzali , glad you found a solution! Do you have an easy example that people in the future might be able to use, any chance?

**Comment by usman-afzali** [comment]
Sure. I just used the following two lines after reference list (of course, looking at your work :))


{{< pagebreak >}}

# Appendix A {.unnumbered}

**Comment by mikemahoney218** [comment]
Perfect, thanks :smile: Might wind up adding an example of this to the example template
